version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
  postgres:
    image: postgres:9.6.6
    restart: always
    volumes:
        - ./data/db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file: ./.env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    command: /venv/bin/gunicorn core.wsgi --bind 0.0.0.0:8000
    depends_on:
      - postgres
  celery_beat:
    restart: always
    build:
      context: .
    command: /venv/bin/celery -A core beat -l INFO
    volumes:
      - .:/django
    container_name: celery_beat
    depends_on:
      - postgres
      - redis
      - app
    environment:
      REDIS_URL: redis://redis:6379/0
  celery_worker:
    restart: always
    build:
      context: .
    command: /venv/bin/celery -A core worker -l INFO
    container_name: celery_worker
    depends_on:
      - postgres
      - redis
      - app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./static/:/var/www/backend/static
    depends_on:
      - app